---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: hello-world-dc
  namespace: testing
spec:
  template:
    metadata:
      labels:
        app: hello-world-dc
    spec: 
      containers:
        - image: python
          imagePullPolicy: Always
          name: hello-world
          command:
            - python
            - '-m'
            - http.server
          readinessProbe:
            initialDelaySeconds: 15
            exec:
              command:
                - /bin/true
          env:
            - name: TEST
              value: test
  triggers:
    - type: ConfigChange
  replicas: 1
  strategy:
    type: Recreate
